---
# Source: helm for kubernetes/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopsoko-88594ebc
  labels:
    app: devopsoko-88594ebc
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: devopsoko-88594ebc
  template:
    metadata:
      labels:
        app: devopsoko-88594ebc
    spec:
      containers:
        - name: devopsoko-88594ebc
          image: docker.io/phengbunath/devopsoko-88594ebc:2
          imagePullPolicy: Always
          ports:
            - containerPort: 3000